# Generated by Django 3.1.3 on 2020-11-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('RUT_cliente', models.CharField(max_length=15, unique=True)),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('ID_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Emision', models.DateTimeField()),
                ('Valor_Total', models.IntegerField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
            ],
            options={
                'db_table': 'Orden_de_Compra',
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('ID_Despacho', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Entrega', models.DateField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('Orden_Compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.orden_compra')),
            ],
            options={
                'db_table': 'Despacho',
            },
        ),
    ]
