# Generated by Django 3.1.3 on 2020-11-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='RUT_cliente',
            new_name='Rut_Cliente',
        ),
    ]
